### ISSUE TITLE
Fail to open the serial port

### ISSUE THREAD

**Issue by Ziyou1987** [stevenwaslander/ros_lightware#1]
Hi, guys

I just purchased a SF10/A ranger finder, which is connected to my laptop with Ubuntu and ROS indigo installed.
When I launched the "altitude_node.launch", I get the error:
"Fail to open the serial port"
Do you have any idea why this occurs? 
Thank you.

**Comment by stevenwaslander** [comment]
Likely your serial port only has root access enabled for security reasons.  Add your user to the group for the associated /dev file.  And see the Clearpath ROS tutorial on udev for more details. http://www.clearpathrobotics.com/blog/udev/

**Comment by Ziyou1987** [comment]
Sorry, it is a rookie mistake. I did not modify the port name in the launch file. Thank you.

**Comment by Ziyou1987** [comment]
Thank you for your reply.
There are two reasons for the failure in my case:
1. I did not change the port number in the launch file;
2. I followed the solution in the link :
http://askubuntu.com/questions/210177/serial-port-terminal-cannot-open-dev-ttys0-permission-denied
to add myself to the dialog group : sudo gpasswd --add ${USER} dialout

**Comment by stevenwaslander** [comment]
Great.
